vscodium:
  pubkey:
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
    filename: vscodium.asc

  repo: https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main

  packages:
    - codium